Repository TechLadies/irrc-madwish, pull requests merged in 2021-02, with the labels that each got.

#88 [IRRC-83] Create modal to show suggested teachers
  backend/src/routes/matching.js
  frontend/src/App.vue
  frontend/src/pages/Matching.vue
Labels: needs-participant-review

#104 Add 'fluent' enum to teacher's English proficiency
  backend/migrations/20210214110931_teachersProficiency.js
  frontend/src/pages/NewTeacher.vue
Labels: ready to merge

#100 [IRRC-94] implemented patchTeacher in vuex, refactored EditTeacher to use vuex
  frontend/src/pages/EditTeacher.vue
  frontend/src/pages/NewStudent.vue
  frontend/src/store/teachers.js
Labels: ready to merge

#115 Fix parsing bug in Matching.vue SecondLanguage
  frontend/src/pages/Matching.vue
Labels: bug, needs-participant-review

#103 [IRRC-91 & 37] Integrate Teacher Profile (update Status)
  backend/src/routes/matches.js
  backend/src/routes/teachers.js
  frontend/src/components/statusCards/StatusCardDroppedOut.vue
  frontend/src/components/statusCards/StatusCardMatched.vue
  frontend/src/components/statusCards/StatusCardUnmatched.vue
  frontend/src/pages/TeacherProfile.vue
  frontend/src/store/students.js
  frontend/src/store/teachers.js
Labels: ready to merge

#83 refactoring students.vue to use Status.vue component
  frontend/src/pages/Students.vue
Labels: ready to merge
