Repository TechLadies/irrc-madwish, pull requests merged in 2021-04, with the labels that each got.

#151 Restore this.getNativeLanguages() in NewStudent.vue
  frontend/src/pages/NewStudent.vue
  frontend/src/pages/NewTeacher.vue
Labels: bug

#156 [IRRC-111, 107, 112] Minor frontend changes - Add student HP no. to Screening.vue, update text for confirmation modals in Screening.vue and Matching.vue
  frontend/src/pages/Matching.vue
  frontend/src/pages/Screening.vue
Labels: ready to merge

#152 [IRRC-104] Fix Status search/filter bug in Teachers.vue
  frontend/src/pages/Teachers.vue
Labels: ready to merge

#161 [IRRC-109 (part 1)] Modified suggested teacher modal + modified matching.vue to use modal component
  frontend/src/components/modals/ModalSuggestedTeachers.vue
  frontend/src/pages/Matching.vue
Labels: ready to merge

#159 [IRRC-21 (story)] Enhancing suggested teacher modal
  frontend/src/components/modals/ModalSuggestedTeachers.vue
  frontend/src/components/statusCards/StatusCardUnmatched.vue
  frontend/src/store/teachers.js
Labels: ready to merge

#157 [IRRC-106] Edit placeholder text for English Proficiency & Native Language in NewStudent.vue
  frontend/src/pages/NewStudent.vue
Labels: ready to merge

#112 Bulk upload Students/Teachers using .csv files
  backend/src/routes/students.js
  backend/src/routes/teachers.js
  frontend/src/assets/seeds/students.csv
  frontend/src/assets/seeds/teachers.csv
  frontend/src/pages/NewStudent.vue
  frontend/src/pages/NewTeacher.vue
Labels: needs-coach-review, needs-participant-review

#163 [IRRC-105] Increase pagination limit on Students.vue & Teachers.vue to 20 rows
  frontend/src/components/PageHeader.vue
  frontend/src/pages/Students.vue
  frontend/src/pages/Teachers.vue
Labels: ready to merge

#165 Fixing bug where teachers with no secondlanguage cannot be displayed on EditTeacher
  frontend/src/store/teachers.js
Labels: ready to merge

#154 [IRRC-108] Changes to NewTeacher and EditTeacher form fields, added TeachingExperience to teacher model
  backend/migrations/20201205141817_teachers.js
  backend/migrations/20210410111727_add_teaching_experience.js
  backend/src/models/teacher.js
  frontend/src/components/ProfileCard.vue
  frontend/src/pages/EditTeacher.vue
  frontend/src/pages/NewTeacher.vue
  frontend/src/pages/TeacherProfile.vue
Labels: ready to merge

#168 Restore Edit links in Student/Teacher profiles
  frontend/src/components/ProfileCard.vue
  frontend/src/pages/StudentProfile.vue
  frontend/src/pages/TeacherProfile.vue
Labels: bug, ready to merge

#172 Patch confirmed date when status is set to Active
  backend/src/helpers/matches.js
  frontend/src/pages/Matching.vue
  frontend/src/store/matching.js
Labels: ready to merge

#171 Force reload after successfully matching student from individual student profile page
  frontend/src/store/matching.js
Labels: ready to merge

#170 Display all teachers if no perfect match for selected student
  frontend/src/components/modals/ModalSuggestedTeachers.vue
Labels: ready to merge

#166 Made reusable NativeLanguageDropdown component
  frontend/src/components/NativeLanguageDropdown.vue
  frontend/src/pages/EditStudent.vue
  frontend/src/pages/EditTeacher.vue
  frontend/src/pages/NewStudent.vue
  frontend/src/pages/NewTeacher.vue
Labels: ready to merge

#169 Add teacher's phone number & double-click on row to link to Teacher's profile page
  frontend/src/pages/Matched.vue
Labels: ready to merge

#177 Add teacher's phone number, removed last email date + from Matched table
  frontend/src/pages/Matched.vue
Labels: needs-coach-review

#179 [Bug] Add showAddLanguage method back to NewTeacher.vue
  frontend/src/pages/NewTeacher.vue
Labels: bug

#175 [IRRC-125] Teacher Experience column in suggested teachers modal
  frontend/src/components/modals/ModalSuggestedTeachers.vue
Labels: conflicts with master
