Repository TechLadies/irrc-madwish, pull requests merged in 2021-03, with the labels that each got.

#111 Clickthrough from Students / Teachers / Screening tables to Profiles
  frontend/src/pages/Screening.vue
  frontend/src/pages/Students.vue
  frontend/src/pages/Teachers.vue
Labels: scratching an itch

#109 Rename StudentProfileCard.vue -> ProfileCard.vue
  frontend/src/components/ProfileCard.vue
  frontend/src/pages/StudentProfile.vue
  frontend/src/pages/TeacherProfile.vue
Labels: scratching an itch

#121 Initialise teachers' status as "Unmatched"
  frontend/src/pages/NewTeacher.vue
Labels: ready to merge

#120 refactored Matching.vue to use Status.vue
  frontend/src/pages/Matching.vue
Labels: ready to merge

#119 IRRC-37/unmatch student flow
  backend/src/routes/matches.js
  frontend/package-lock.json
  frontend/src/store/students.js
  frontend/src/store/teachers.js
Labels: ready to merge

#102 [IRRC-84] logic for suggested teachers for matching
  frontend/src/pages/Teachers.vue
  frontend/src/store/teachers.js
Labels: needs-participant-review

#125 Create teacher without SecondLanguage or LanguageProficiency in NewTeacher.vue
  frontend/src/pages/NewTeacher.vue
Labels: ready to merge

#106 [IRRC-101] abstract out suggested teacher modal
  backend/src/helpers/statusUpdates.js
  backend/src/routes/statusUpdates.js
  backend/src/routes/teachers.js
  frontend/src/components/modals/ModalSuggestedTeachers.vue
  frontend/src/components/statusCards/StatusCardUnmatched.vue
  frontend/src/pages/StudentProfile.vue
  frontend/src/pages/Students.vue
  frontend/src/pages/Teachers.vue
  frontend/src/store/students.js
  frontend/src/store/teachers.js
Labels: ready to merge

#128 [Refactor] Move generic helpers out of helpers/students
  backend/src/helpers/nativeLanguages.js
  backend/src/helpers/statuses.js
  backend/src/helpers/students.js
  backend/src/helpers/teachers.js
  backend/src/routes/students.js
  backend/src/routes/teachers.js
Labels: ready to merge, scratching an itch

#133 Issue 131 for filtering out dropped out teachers in suggestedTeachers
  frontend/src/pages/Matching.vue
  frontend/src/store/teachers.js
Labels: ready to merge

#134 [IRRC-100] Show teacher's name on matched student's profile
  frontend/src/App.vue
  frontend/src/components/statusCards/StatusCardMatched.vue
  frontend/src/store/matches.js
Labels: ready to merge

#138 add pagination to Teachers + update helpers for statuses and nativeLanguages
  backend/src/helpers/nativeLanguages.js
  backend/src/helpers/statuses.js
  backend/src/routes/statusUpdates.js
  backend/src/routes/teachers.js
  frontend/src/pages/Teachers.vue
Labels: needs-participant-review

#135 [Matched Table] Update styling for "Confirmation" column
  backend/src/helpers/matches.js
  backend/src/routes/matches.js
  frontend/src/components/MatchStatus.vue
  frontend/src/components/Status.vue
  frontend/src/pages/Matched.vue
  frontend/src/store/matches.js
Labels: conflicts with master

#136 [IRRC-103] Refactor New Student page and Notification UI
  frontend/src/pages/NewStudent.vue
  frontend/src/store/students.js
Labels: ready to merge

#132 Move function to disable input for second language proficiency to a watch method
  frontend/src/pages/NewTeacher.vue
Labels: bug, question, ready to merge

#137 Force correct reload on Matching.vue and Screening.vue pages
  frontend/src/pages/Matching.vue
  frontend/src/pages/Screening.vue
Labels: bug, ready to merge, scratching an itch

#147 Delete components/StudentHistory.vue
  frontend/src/components/StudentHistory.vue
Labels: scratching an itch

#145 Add match from student profile
  backend/src/helpers/statusUpdates.js
  backend/src/routes/matches.js
  frontend/src/components/modals/ModalDroppedOut.vue
  frontend/src/components/statusCards/StatusCardScreening.vue
  frontend/src/components/statusCards/StatusCardUnmatched.vue
  frontend/src/pages/Matching.vue
  frontend/src/store/matching.js
  frontend/src/store/students.js
Labels: bug, needs-participant-review

#148 Handle null secondLanguage in TeacherProfile.vue
  frontend/src/components/modals/ModalDroppedOut.vue
  frontend/src/components/statusCards/StatusCardDroppedOut.vue
  frontend/src/components/statusCards/StatusCardMatched.vue
  frontend/src/components/statusCards/StatusCardScreening.vue
  frontend/src/components/statusCards/StatusCardUnmatched.vue
  frontend/src/pages/StudentProfile.vue
  frontend/src/pages/Students.vue
  frontend/src/pages/TeacherProfile.vue
  frontend/src/pages/Teachers.vue
  frontend/src/store.js
  frontend/src/store/students.js
Labels: bug, ready to merge, scratching an itch

#139 Default student FirstName to FullName when rolling back migration
  backend/migrations/20201107134701_remove_firstName_lastName_from_students.js
Labels: bug, ready to merge
